#!/bin/bash
stackname=$1

if [[  -z $stackname ]]
then
        echo "usage: $0 <stackname>"
        exit 1
fi

aws cloudformation update-stack --region eu-west-1 --stack-name $stackname --use-previous-template \
    --capabilities "CAPABILITY_IAM" \
    --parameters ParameterValue=$version,ParameterKey=dockerImageVersion
